"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEPRECATED_Response = exports.DEPRECATED_request = exports.LeagueWebSocket = exports.createWebSocketConnection = exports.Http2Response = exports.createHttpSession = exports.createHttp2Request = exports.Http1Response = exports.createHttp1Request = exports.LeagueClient = exports.InvalidPlatformError = exports.ClientNotFoundError = exports.authenticate = void 0;
var authentication_1 = require("./authentication");
Object.defineProperty(exports, "authenticate", { enumerable: true, get: function () { return authentication_1.authenticate; } });
Object.defineProperty(exports, "ClientNotFoundError", { enumerable: true, get: function () { return authentication_1.ClientNotFoundError; } });
Object.defineProperty(exports, "InvalidPlatformError", { enumerable: true, get: function () { return authentication_1.InvalidPlatformError; } });
var client_1 = require("./client");
Object.defineProperty(exports, "LeagueClient", { enumerable: true, get: function () { return client_1.LeagueClient; } });
var http_1 = require("./http");
Object.defineProperty(exports, "createHttp1Request", { enumerable: true, get: function () { return http_1.createHttp1Request; } });
Object.defineProperty(exports, "Http1Response", { enumerable: true, get: function () { return http_1.Http1Response; } });
var http2_1 = require("./http2");
Object.defineProperty(exports, "createHttp2Request", { enumerable: true, get: function () { return http2_1.createHttp2Request; } });
Object.defineProperty(exports, "createHttpSession", { enumerable: true, get: function () { return http2_1.createHttpSession; } });
Object.defineProperty(exports, "Http2Response", { enumerable: true, get: function () { return http2_1.Http2Response; } });
var websocket_1 = require("./websocket");
Object.defineProperty(exports, "createWebSocketConnection", { enumerable: true, get: function () { return websocket_1.createWebSocketConnection; } });
Object.defineProperty(exports, "LeagueWebSocket", { enumerable: true, get: function () { return websocket_1.LeagueWebSocket; } });
var request_deprecated_1 = require("./request_deprecated");
Object.defineProperty(exports, "DEPRECATED_request", { enumerable: true, get: function () { return request_deprecated_1.DEPRECATED_request; } });
Object.defineProperty(exports, "DEPRECATED_Response", { enumerable: true, get: function () { return request_deprecated_1.DEPRECATED_Response; } });
