export {createMainWindow} from './home'
export {createAssistWindow} from './assist'
export {makeTray} from './makeTray'
export {listenIpc} from './listenCommonIpc'
export {matchHistoryIpc,creatMatchAfterStartGame} from './matchHistory'
export {queryMatchIpc} from './queryMatch'
